// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXzGHuy9iowbBwFvVKPmjveCTRyEtTRU0',
    appId: '1:652371195297:web:668d5b2052aa1a01c5c7e0',
    messagingSenderId: '652371195297',
    projectId: 'auth-project-1bc2b',
    authDomain: 'auth-project-1bc2b.firebaseapp.com',
    storageBucket: 'auth-project-1bc2b.appspot.com',
    measurementId: 'G-CKVYTHK248',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3X4UQhgploXjmtFdg0AA6Y0m5Jddvy2Q',
    appId: '1:652371195297:android:753a967c395d2533c5c7e0',
    messagingSenderId: '652371195297',
    projectId: 'auth-project-1bc2b',
    storageBucket: 'auth-project-1bc2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLDz9_94LwLEln6awlGb6776_oP2qXMfE',
    appId: '1:652371195297:ios:bd173170f9e3e7abc5c7e0',
    messagingSenderId: '652371195297',
    projectId: 'auth-project-1bc2b',
    storageBucket: 'auth-project-1bc2b.appspot.com',
    iosClientId:
        '652371195297-d7qqlfktt02qpad2rern79covj2ts9a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.authProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLDz9_94LwLEln6awlGb6776_oP2qXMfE',
    appId: '1:652371195297:ios:bd173170f9e3e7abc5c7e0',
    messagingSenderId: '652371195297',
    projectId: 'auth-project-1bc2b',
    storageBucket: 'auth-project-1bc2b.appspot.com',
    iosClientId:
        '652371195297-d7qqlfktt02qpad2rern79covj2ts9a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.authProject',
  );
}
